template: Hello, %s!

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost/example

  properties:
    # Use a custom dialect to change default string type from "varchar(255)" to "varchar"
    hibernate.dialect: com.davidtrott.example.database.util.CustomPostgreSQLDialect
    # Change search path to place new tables in the "example" schema
    currentSchema: example,public
    # Instruct hibernate to update the database schema automatically on app startup
    hibernate.hbm2ddl.auto: update
    charSet: UTF-8

  validationQuery: "SELECT 1"
  maxWaitForConnection: 1s
  checkConnectionWhileIdle: false
  minSize: 8
  maxSize: 32
